version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  # Espresso instrumented tests configuration
  # https://medium.com/android-testing-daily/running-espresso-tests-on-circle-ci-ec919f85a116
  test:
    override:
      # start the emulator
      - emulator -avd circleci-android22 -no-audio -no-window:
          background: true
          parallel: true
      # wait for it to have booted
      - circle-android wait-for-boot
      # unlock the emulator screen
      - sleep 30
      - adb shell input keyevent 82
      # run tests  against the emulator.
      - ./gradlew connectedAndroidTest -PdisablePreDex
      # copy the build outputs to artifacts
      - cp -r app/build/outputs $CIRCLE_ARTIFACTS
      # copy the test results to the test results directory.
      - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS